import { Injectable } from '@angular/core';
import { Recipe } from '../models';

@Injectable({ providedIn: 'root' })
export class ExampleService {
  public getExampleData(): Recipe[] {
    return [
      {
        name: 'Chocolate Cake',
        type: 'Cakes',
        mainIngredient: 'Chocolate',
        occasion: 'Birthday',
        difficulty: 2,
        dateAdded: new Date(2022, 5, 3),
      },
      {
        name: 'Pumpkin Cupcakes',
        type: 'Cupcakes',
        mainIngredient: 'Pumpkin',
        occasion: 'Halloween',
        difficulty: 2,
        dateAdded: new Date(2017, 10, 15),
      },
      {
        name: 'Pumpkin Pie',
        type: 'Pies',
        mainIngredient: 'Pumpkin',
        occasion: 'Thanksgiving',
        difficulty: 2,
        dateAdded: new Date(2010, 11, 9),
      },
      {
        name: 'Cranberry Orange Cookies',
        type: 'Cookies',
        mainIngredient: 'Cranberry',
        occasion: 'Christmas',
        difficulty: 2,
        dateAdded: new Date(2020, 12, 7),
      },
      {
        name: 'Chocolate Raspberry Cake',
        type: 'Cookies',
        mainIngredient: 'Raspberry',
        occasion: "Valentine's Day",
        difficulty: 3,
        dateAdded: new Date(2023, 2, 14),
      },
      {
        name: 'Fudge Brownies',
        type: 'Brownies & Bars',
        mainIngredient: 'Chocolate',
        difficulty: 2,
        dateAdded: new Date(2021, 8, 10),
      },
      {
        name: 'Caramel Sauce',
        type: 'Sauces',
        mainIngredient: 'Sugar',
        difficulty: 2,
        dateAdded: new Date(2018, 3, 22),
      },
      {
        name: 'Chocolate Chip Cookies',
        type: 'Cookies',
        mainIngredient: 'Chocolate Chips',
        difficulty: 2,
        dateAdded: new Date(2015, 6, 18),
      },
      {
        name: 'Apple Cake',
        type: 'Cakes',
        mainIngredient: 'Apple',
        occasion: 'Christmas',
        difficulty: 2,
        dateAdded: new Date(2019, 12, 24),
      },
      {
        name: 'Pecan Pie',
        type: 'Pies',
        mainIngredient: 'Pecan',
        occasion: '',
        difficulty: 2,
        dateAdded: new Date(2018, 11, 1),
      },
      {
        name: 'Bourbon Pecan Pie',
        type: 'Pies',
        mainIngredient: 'Bourbon',
        occasion: 'Thanksgiving',
        difficulty: 2,
        dateAdded: new Date(2019, 12, 22),
      },
      {
        name: 'Cake Pops',
        type: 'Cakes',
        mainIngredient: 'Sprinkles',
        occasion: 'Birthday',
        difficulty: 2,
        dateAdded: new Date(2020, 5, 1),
      },
      {
        name: 'Salted Caramel Tart',
        type: 'Tarts',
        mainIngredient: 'Caramel',
        occasion: '',
        difficulty: 3,
        dateAdded: new Date(2014, 8, 7),
      },
      {
        name: 'Key Lime Pie',
        type: 'Pies',
        mainIngredient: 'Key Lime',
        occasion: 'Easter',
        difficulty: 2,
        dateAdded: new Date(2022, 12, 12),
      },
      {
        name: 'Blueberry Sauce',
        type: 'Sauces',
        mainIngredient: 'Blueberry',
        occasion: '',
        difficulty: 1,
        dateAdded: new Date(2023, 2, 9),
      },
      {
        name: 'Honey Butter',
        type: 'Sauces',
        mainIngredient: 'Honey',
        occasion: '',
        difficulty: 1,
        dateAdded: new Date(2024, 9, 2),
      },
      {
        name: 'Chocolate Ganache',
        type: 'Sauces',
        mainIngredient: 'Chocolate',
        occasion: '',
        difficulty: 2,
        dateAdded: new Date(2016, 4, 12),
      },
      {
        name: 'Lemon Curd',
        type: 'Sauces',
        mainIngredient: 'Lemon',
        occasion: '',
        difficulty: 1,
        dateAdded: new Date(2019, 3, 14),
      },
      {
        name: 'Lemon Bars',
        type: 'Brownies & Bars',
        mainIngredient: 'Lemon',
        occasion: '',
        difficulty: 2,
        dateAdded: new Date(2019, 3, 14),
      },
      {
        name: 'Cinnamon Toast Crunch Cheesecake',
        type: 'Cheesecake',
        mainIngredient: ' Cinnamon Toast Crunch',
        occasion: 'Easter',
        difficulty: 3,
        dateAdded: new Date(2024, 2, 20),
      },
      {
        name: 'Carrot Cake',
        type: 'Cakes',
        mainIngredient: 'Carrot',
        occasion: 'Birthday',
        difficulty: 3,
        dateAdded: new Date(2020, 9, 17),
      },
    ];
  }
}
