import { HttpClient } from '@angular/common/http';
import { Injectable } from '@angular/core';
import { catchError, Observable, of, throwError } from 'rxjs';
import { Recipe, SearchResult } from '../models';

const RECIPES_DUMMY_DATA: Recipe[] = [
  {
    slug: 'brownies',
    name: 'Brownies',
    imageUrl: 'assets/images/bars/brownies.png',
    categories: ['bars'],
    flavors: ['chocolate'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'lemon-bars',
    name: 'Lemon Bars',
    imageUrl: 'assets/images/bars/lemon-bars.jpg',
    categories: ['bars'],
    flavors: ['citrus'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'millionaire-shortbread',
    name: 'Millionaire Shortbread',
    imageUrl: 'assets/images/bars/millionaire-shortbread.jpg',
    categories: ['bars'],
    flavors: ['chocolate'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'chocolate-raspberry-cake',
    name: 'Chocolate Raspberry Cake',
    imageUrl: 'assets/images/cakes/chocolate-raspberry-cake.jpg',
    categories: ['cake'],
    occasion: ['birthday'],
    flavors: ['chocolate', 'fruity'],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'banana-bread',
    name: 'Banana Bread',
    imageUrl: 'assets/images/bread/banana-bread.png',
    categories: ['bread'],
    flavors: ['fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'banana-scones',
    name: 'Banana Scones',
    imageUrl: 'assets/images/breakfast/banana-scones.jpg',
    categories: ['breakfast'],
    flavors: ['fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'apple-cake',
    name: 'Apple Cake',
    imageUrl: 'assets/images/cakes/apple-cake.jpg',
    categories: ['cake'],
    flavors: ['fruity', 'spiced'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'banana-sheet-cake',
    name: 'Banana Sheet Cake',
    imageUrl: 'assets/images/cakes/banana-sheet-cake.jpg',
    categories: ['cake'],
    flavors: ['fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'carrot-cake',
    name: 'Carrot Cake',
    imageUrl: 'assets/images/cakes/carrot-cake.jpg',
    categories: ['cake'],
    flavors: ['spiced'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'christmas-cake',
    name: 'Christmas Cake',
    imageUrl: 'assets/images/cakes/christmas-cake.jpg',
    categories: ['cake'],
    flavors: ['nutty', 'fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'lemon-blueberry-cake',
    name: 'Lemon Blueberry Cake',
    imageUrl: 'assets/images/cakes/lemon-blueberry-cake.png',
    categories: ['cake'],
    flavors: ['citrus', 'fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'pineapple-cake',
    name: 'Pineapple Cake',
    imageUrl: 'assets/images/cakes/pineapple-cake.jpg',
    categories: ['cake'],
    flavors: ['fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'basque-cheesecake',
    name: 'Basque Cheesecake',
    imageUrl: 'assets/images/cheesecakes/basque-cheesecake.jpg',
    categories: ['cheesecake'],
    flavors: ['rich'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'blueberry-cheesecake',
    name: 'Blueberry Cheesecake',
    imageUrl: 'assets/images/cheesecakes/blueberry-cheesecake.jpg',
    categories: ['cheesecake'],
    flavors: ['fruity', 'rich'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'cinnamon-toast-crunch-cheesecake',
    name: 'Cinnamon Toast Crunch Cheesecake',
    imageUrl: 'assets/images/cheesecakes/cheesecake.jpg',
    categories: ['cheesecake'],
    flavors: ['spiced', 'rich'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'chocolate-chunk-cookies',
    name: 'Chocolate Chunk Cookies',
    imageUrl: 'assets/images/cookies/chocolate-chunk-cookies.jpg',
    categories: ['cookies'],
    flavors: ['chocolate'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'chocolate-oatmeal-cookies',
    name: 'Chocolate Oatmeal Cookies',
    imageUrl: 'assets/images/cookies/chocolate-oatmeal-cookies.jpg',
    categories: ['cookies'],
    flavors: ['chocolate', 'spiced'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'chocolate-peppermint-cookies',
    name: 'Chocolate Peppermint Cookies',
    imageUrl: 'assets/images/cookies/chocolate-peppermint-cookies.jpg',
    categories: ['cookies'],
    flavors: ['chocolate', 'fresh'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'gingersnaps',
    name: 'Gingersnaps',
    imageUrl: 'assets/images/cookies/gingersnaps.jpg',
    categories: ['cookies'],
    flavors: ['spiced'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'snickerdoodles',
    name: 'Snickerdoodles',
    imageUrl: 'assets/images/cookies/snickerdoodles.jpg',
    categories: ['cookies'],
    flavors: ['spiced'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'xmas-cookies',
    name: 'Christmas Cookies',
    imageUrl: 'assets/images/cookies/xmas-cookies.jpg',
    categories: ['cookies'],
    flavors: ['spiced', 'chocolate'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'pecan-pie',
    name: 'Pecan Pie',
    imageUrl: 'assets/images/pies/pecan-pie2.png',
    categories: ['pie'],
    flavors: ['nutty'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'bourbon-pecan-pie',
    name: 'Bourbon Pecan Pie',
    imageUrl: 'assets/images/pies/bourbon-pecan-pie.jpg',
    categories: ['pie'],
    flavors: ['nutty'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'key-lime-pie',
    name: 'Key Lime Pie',
    imageUrl: 'assets/images/pies/key-lime-pie.jpg',
    categories: ['pie'],
    flavors: ['citrus', 'rich'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'apple-tart-tatin',
    name: 'Apple Tart Tatin',
    imageUrl: 'assets/images/tarts/apple-tart-tatin.jpg',
    categories: ['tart'],
    flavors: ['fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'apple-tart',
    name: 'French Apple Tart',
    imageUrl: 'assets/images/tarts/apple-tart.jpg',
    categories: ['tart'],
    flavors: ['fruity'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'chocolate-tart',
    name: 'Rich Chocolate Tart',
    imageUrl: 'assets/images/tarts/chocolate-tart.jpg',
    categories: ['tart'],
    flavors: ['chocolate'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
  {
    slug: 'fruit-tart',
    name: 'Fruit Tart with Shortbread Crust',
    imageUrl: 'assets/images/tarts/tart.jpg',
    categories: ['tart'],
    flavors: ['fruity', 'fresh'],
    occasion: [],
    ingredientSections: [],
    stepSections: [],
  },
];

@Injectable({ providedIn: 'root' })
export class RecipesService {
  constructor(private http: HttpClient) {}

  public getRecipes(): Observable<Recipe[]> {
    return of(RECIPES_DUMMY_DATA);
  }

  public searchRecipes(): Observable<SearchResult[]> {
    // Simulate a search operation
    return of(
      RECIPES_DUMMY_DATA.map((recipe) => ({
        slug: recipe.slug,
        name: recipe.name,
        category: 'recipes',
        imageUrl: recipe.imageUrl,
        link: `/recipe/${recipe.slug}`,
      }))
    );
  }

  getRecipe(slug: string): Observable<Recipe> {
    const url = `assets/recipes/${slug}.json`;
    return this.http.get<Recipe>(url).pipe(
      catchError((err) => {
        console.error(`Error loading recipe for slug: ${slug}`, err);
        return throwError(() => new Error('Recipe not found.'));
      })
    );
  }
}
